// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prescriptions.Models;

#nullable disable

namespace Prescriptions.Migrations
{
    [DbContext(typeof(PrescriptionDatabaseContext))]
    [Migration("20250921202645_WalgreensPrescription")]
    partial class WalgreensPrescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Prescriptions.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("FillStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PrescriptionId");

                    b.ToTable("Prescription");

                    b.HasData(
                        new
                        {
                            PrescriptionId = 1,
                            Cost = 15.300000000000001,
                            FillStatus = "Pending",
                            MedicationName = "Lisinopril",
                            RequestTime = "2025-10-01"
                        },
                        new
                        {
                            PrescriptionId = 2,
                            Cost = 25.0,
                            FillStatus = "Filled",
                            MedicationName = "Atorvastatin",
                            RequestTime = "2025-09-28"
                        },
                        new
                        {
                            PrescriptionId = 3,
                            Cost = 18.75,
                            FillStatus = "Denied",
                            MedicationName = "Albuterol",
                            RequestTime = "2025-09-27"
                        },
                        new
                        {
                            PrescriptionId = 4,
                            Cost = 12.4,
                            FillStatus = "Pending",
                            MedicationName = "Omeprazole",
                            RequestTime = "2025-10-02"
                        },
                        new
                        {
                            PrescriptionId = 5,
                            Cost = 30.5,
                            FillStatus = "Filled",
                            MedicationName = "Levothyroxine",
                            RequestTime = "2025-09-25"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
